# CEE6501 — Coding Assignment, Week 2

**Assigned:** 01/23/2026 (Week 2)  
**Due:** 02/02/2026

**Canvas Submission Link:**  <https://gatech.instructure.com/courses/517856/assignments/2320758>

---

## Logistics

### 💻 Assignment Format

This is a **coding assignment**.

- Complete the assignment by **executing and completing all tasks in the notebook cells below**
- The notebook should be run and completed in **Google Colab**
- Your submission **must be a link to a functioning Google Colab notebook**

You may use any local tools (VS Code, JupyterLab, etc.) while working, but the **final submitted work must run correctly in Colab**.


### 📤 Submission Instructions

- Submit **one link** to your Google Colab notebook on Canvas
- Ensure that:
  - All cells run **top-to-bottom without errors**
  - All required outputs are visible
  - The notebook reflects your final answers

### ✅ Checklist Before Submitting

- [ ] All notebook cells completed
- [ ] Code runs without errors from a fresh runtime
- [ ] Outputs and plots are clearly visible
- [ ] Colab link opens and runs correctly
- [ ] Correct notebook submitted on Canvas

### 🤝 Collaboration / AI tools
You may discuss concepts with classmates and you may use AI tools to help you learn,
but **your submitted code must be written by you and you must understand it**.
If you used outside help, add a short note in the final reflection cell.

---

## --- Google Colab environment setup ---

The cell below only needs to run when the notebook is opened in Google Colab.

This code will not affect code execution locally in VS-code + conda environment.

Google Colab starts each session with its own **preloaded versions** of common Python (currently 3.12.12) and Python packages (NumPy, SciPy, etc.).  
If we install different package versions once loaded, Python cannot switch to them while it is already running.

### What will happen
When you run the setup cell below in Google Colab:

1. The required package versions are installed
2. The runtime is **automatically restarted** so the new versions can be loaded  
3. You may see the message **“Your session crashed for an unknown reason.”**  
   → This is expected and normal

After the restart, rerun the notebook and check the **version check cell** to confirm package versions are correct.

### Runtime menu notes
- **Runtime → Restart session**  
  Restarts Python but keeps installed packages and saved files

- **Runtime → Disconnect and delete runtime**  
  Resets Colab completely to its default environment (packages will need to be reinstalled)

In [203]:
# ============================================================
# Google Colab environment setup (pinned versions)
# ============================================================

import sys
import os
import subprocess

if "google.colab" in sys.modules:
    print("Running in Google Colab")
    print("Python version:", sys.version.split()[0])

    # ---- Required package versions --------------------------
    requirements = {
        "numpy": "2.4.0",
        "scipy": "1.16.3",
        "matplotlib": "3.10.8",
        "pandas": "2.3.3",
    }

    # ---- Check currently loaded versions --------------------
    restart_needed = False

    for pkg, required_version in requirements.items():
        try:
            module = __import__(pkg)
            installed_version = module.__version__
        except Exception:
            installed_version = None

        print(f"{pkg}: {installed_version} (required: {required_version})")

        if installed_version != required_version:
            restart_needed = True

    # ---- Install if needed ----------------------------------
    if restart_needed:
        print("\nInstalling pinned package versions...")

        pip_args = [
            f"{pkg}=={ver}" for pkg, ver in requirements.items()
        ]

        subprocess.check_call(
            [sys.executable, "-m", "pip", "install", "-q", *pip_args]
        )

        print("Installation complete.")
        print("Restarting runtime to load correct packages...")

        # This will appear as a "crash" in Colab — expected behavior
        os.kill(os.getpid(), 9)

    else:
        print("\nAll required package versions already installed.")

else:
    print("Not running in Google Colab — setup skipped.")
    print("Python version:", sys.version.split()[0])

Not running in Google Colab — setup skipped.
Python version: 3.12.12


In [204]:
# --- Version check ---
import numpy
import scipy
import matplotlib
import pandas

print("numpy:", numpy.__version__)
print("scipy:", scipy.__version__)
print("matplotlib:", matplotlib.__version__)
print("pandas:", pandas.__version__)

numpy: 2.4.0
scipy: 1.16.3
matplotlib: 3.10.8
pandas: 2.3.3


---

## Imports

Run this cell once before starting the assignment.

In [205]:
import numpy as np

# Make prints easier to read
np.set_printoptions(precision=6, suppress=True)


---

## Question 1 — Matrix Partitioner (Split into 4 blocks) (20 pts)

Write a function that takes **any** matrix and splits it into **four blocks**:

$$
\mathbf{A}
=
\begin{bmatrix}
\mathbf{A}_{11} & \mathbf{A}_{12}\\
\mathbf{A}_{21} & \mathbf{A}_{22}
\end{bmatrix}
$$

### Requirements

- Function name: `partition4(A, r_split, c_split)`
- Inputs:
  - `A`: a 2D NumPy array of shape `(m, n)`
  - `r_split`: row split index (an integer in `[1, m-1]`)
  - `c_split`: column split index (an integer in `[1, n-1]`)
- Output:
  - a tuple `(A11, A12, A21, A22)`

### Notes
- `A11` should contain rows `0..r_split-1` and cols `0..c_split-1`
- `A12` should contain rows `0..r_split-1` and cols `c_split..n-1`
- `A21` should contain rows `r_split..m-1` and cols `0..c_split-1`
- `A22` should contain rows `r_split..m-1` and cols `c_split..n-1`

✅ Deliverable: Implement `partition4` so the test cell passes.

In [206]:
# YOUR WORK

def partition4(A, r_split, c_split):
    """Split A into four blocks using row/col split indices.
    
    Returns (A11, A12, A21, A22).
    """
    A11 = A[:r_split, :c_split]
    A12 = A[:r_split, c_split:]
    A21 = A[r_split:, :c_split]
    A22 = A[r_split:, c_split:]
    return (A11, A12, A21, A22)

    # TODO: implement
    raise NotImplementedError


In [207]:
# ============================================================
#  TESTS — Do Not Edit
# ============================================================

print("\n--- Matrix Partitioner Tests ---")

# ------------------------------------------------------------
# Test matrix (known values, easy to spot-check)
# ------------------------------------------------------------

A = np.arange(1, 1 + 6 * 5).reshape(6, 5)  # 6x5 matrix with entries 1..30

print("\nMatrix A (6×5):")
print(A)

# Partition A into 4 blocks using the provided split indices
# r_split=4  -> top block has 4 rows, bottom has 2 rows
# c_split=2  -> left block has 2 cols, right has 3 cols
A11, A12, A21, A22 = partition4(A, r_split=4, c_split=2)

print("\nBlocks:")
print("A11 (top-left):")
print(A11)
print("\nA12 (top-right):")
print(A12)
print("\nA21 (bottom-left):")
print(A21)
print("\nA22 (bottom-right):")
print(A22)

# ------------------------------------------------------------
# Shape checks
# ------------------------------------------------------------

assert isinstance(A11, np.ndarray), "A11 must be a NumPy array"
assert isinstance(A12, np.ndarray), "A12 must be a NumPy array"
assert isinstance(A21, np.ndarray), "A21 must be a NumPy array"
assert isinstance(A22, np.ndarray), "A22 must be a NumPy array"

assert A11.shape == (4, 2), "A11 should have shape (4, 2)"
assert A12.shape == (4, 3), "A12 should have shape (4, 3)"
assert A21.shape == (2, 2), "A21 should have shape (2, 2)"
assert A22.shape == (2, 3), "A22 should have shape (2, 3)"

print("✔ Shape checks passed")

# ------------------------------------------------------------
# Content checks (spot checks: corners + a few interior points)
# ------------------------------------------------------------

# A11 (rows 0..3, cols 0..1)
assert A11[0, 0] == A[0, 0], "A11[0,0] mismatch"
assert A11[3, 1] == A[3, 1], "A11[3,1] mismatch"

# A12 (rows 0..3, cols 2..4)
assert A12[0, 0] == A[0, 2], "A12[0,0] mismatch"
assert A12[3, 2] == A[3, 4], "A12[3,2] mismatch"

# A21 (rows 4..5, cols 0..1)
assert A21[0, 0] == A[4, 0], "A21[0,0] mismatch"
assert A21[0, 1] == A[4, 1], "A21[0,1] mismatch"

# A22 (rows 4..5, cols 2..4)
assert A22[1, 0] == A[5, 2], "A22[1,0] mismatch"
assert A22[1, 2] == A[5, 4], "A22[1,2] mismatch"

print("✔ Content spot-checks passed")

# ------------------------------------------------------------
# Reconstruction check (block concatenation must recover A)
# ------------------------------------------------------------

A_rebuild = np.block([
    [A11, A12],
    [A21, A22],
])

np.testing.assert_array_equal(A_rebuild, A)
print("✔ Reconstruction check passed")

print("\n✅ Question 1 tests passed.")



--- Matrix Partitioner Tests ---

Matrix A (6×5):
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]

Blocks:
A11 (top-left):
[[ 1  2]
 [ 6  7]
 [11 12]
 [16 17]]

A12 (top-right):
[[ 3  4  5]
 [ 8  9 10]
 [13 14 15]
 [18 19 20]]

A21 (bottom-left):
[[21 22]
 [26 27]]

A22 (bottom-right):
[[23 24 25]
 [28 29 30]]
✔ Shape checks passed
✔ Content spot-checks passed
✔ Reconstruction check passed

✅ Question 1 tests passed.


---

## Question 2 — Gauss–Jordan Inverse (40 pts)

Implement Gauss–Jordan elimination on the augmented system $[\mathbf{A}\,|\,\mathbf{I}]$ to compute $\mathbf{A}^{-1}$.

### Requirements

- Function name: `gauss_jordan_inverse(A)`
- Input:
  - `A`: a square NumPy array `(n, n)`
- Output:
  - `invA`: a NumPy array `(n, n)`

### Notes
- You may **not** call `np.linalg.inv` inside your implementation.

### Checks
You will test your solver on:
1. A small matrix (same as a written-assignment example)
$$
\mathbf{A}=
\begin{bmatrix}
2 & 1 & 0 & 1 \\
1 & 3 & 1 & 0 \\
0 & 2 & 4 & 1 \\
1 & 0 & 1 & 2
\end{bmatrix}
$$
2. A larger random matrix

✅ Deliverable: Implement `gauss_jordan_inverse` so the test cell passes.

In [208]:
# YOUR WORK

def gauss_jordan_inverse(A, tol=1e-14):
    """
    Compute A^{-1} using Gauss–Jordan elimination on [A | I].
    """
    n = A.shape[0]
    AI = np.hstack([A, np.eye(n)])
    
    for j in range(n):
        pivot_row = j + np.argmax(np.abs(AI[j:, j]))
        if pivot_row != j:
            AI[[j, pivot_row]] = AI[[pivot_row, j]]

        pivot = AI[j, j]
        AI[j, :] = AI[j, :] / pivot

        for i in range(n):
            if i == j:
                continue
            factor = AI[i, j]
            AI[i, :] = AI[i, :] - factor * AI[j, :]

    invA = AI[:, n:]
    return invA

    # TODO: implement
    raise NotImplementedError


In [209]:
# ============================================================
#  TESTS — Do Not Edit
# ============================================================

print("\n--- Gauss–Jordan Inverse Solver Tests ---")

# ------------------------------------------------------------
# Small test case (matches written-assignment matrix)
# ------------------------------------------------------------

A_small = np.array([
    [2.0, 1.0, 0.0, 1.0],
    [1.0, 3.0, 1.0, 0.0],
    [0.0, 2.0, 4.0, 1.0],
    [1.0, 0.0, 1.0, 2.0],
])

print("\nMatrix A_small:")
print(A_small)

# Compute inverse using Gauss–Jordan
inv_gj_small = gauss_jordan_inverse(A_small)

# Reference inverse using NumPy
inv_np_small = np.linalg.inv(A_small)

# ------------------------------------------------------------
# Display results (small system)
# ------------------------------------------------------------

print("\nInverse via Gauss–Jordan:")
print(np.round(inv_gj_small, 6))

print("\nInverse via NumPy:")
print(np.round(inv_np_small, 6))

# Residual check: I − A A^{-1}
res_small = np.linalg.norm(np.eye(4) - A_small @ inv_gj_small)

print("\nResidual ||I − A A^{-1}|| =", res_small)

# ------------------------------------------------------------
# Numerical correctness checks (small system)
# ------------------------------------------------------------

np.testing.assert_allclose(
    inv_gj_small, inv_np_small,
    rtol=1e-9,
    atol=1e-9,
    err_msg="Gauss–Jordan inverse does not match NumPy inverse (small case)"
)

assert res_small < 1e-8, "Residual too large for small inverse test"

print("✔ Small-matrix inverse checks passed")

# ------------------------------------------------------------
# Larger random test (stability + scaling)
# ------------------------------------------------------------

print("\n--- Large random matrix test ---")

rng = np.random.default_rng(6501)
n = 30
A_big = rng.normal(size=(n, n))

# Compute inverses
inv_gj_big = gauss_jordan_inverse(A_big)
inv_np_big = np.linalg.inv(A_big)

# ------------------------------------------------------------
# Numerical correctness checks (large system)
# ------------------------------------------------------------

np.testing.assert_allclose(
    inv_gj_big, inv_np_big,
    rtol=1e-7,
    atol=1e-7,
    err_msg="Gauss–Jordan inverse does not match NumPy inverse (large case)"
)

# Relative residual check
res_big = np.linalg.norm(np.eye(n) - A_big @ inv_gj_big) / np.linalg.norm(np.eye(n))
assert res_big < 1e-7, "Relative residual too large for large inverse test"

print("Relative residual (large system):", res_big)

print("\n✅ Question 2 tests passed.")



--- Gauss–Jordan Inverse Solver Tests ---

Matrix A_small:
[[2. 1. 0. 1.]
 [1. 3. 1. 0.]
 [0. 2. 4. 1.]
 [1. 0. 1. 2.]]

Inverse via Gauss–Jordan:
[[ 1.214286 -0.642857  0.357143 -0.785714]
 [-0.571429  0.714286 -0.285714  0.428571]
 [ 0.5      -0.5       0.5      -0.5     ]
 [-0.857143  0.571429 -0.428571  1.142857]]

Inverse via NumPy:
[[ 1.214286 -0.642857  0.357143 -0.785714]
 [-0.571429  0.714286 -0.285714  0.428571]
 [ 0.5      -0.5       0.5      -0.5     ]
 [-0.857143  0.571429 -0.428571  1.142857]]

Residual ||I − A A^{-1}|| = 7.928578270080922e-16
✔ Small-matrix inverse checks passed

--- Large random matrix test ---
Relative residual (large system): 3.965217344477958e-15

✅ Question 2 tests passed.


### Timing comparison (just for information)

Run the cell below to compare your Gauss–Jordan inverse with NumPy on a larger matrix.
You should see NumPy much faster.

✅ Deliverable: print the timing ratio `time_gj / time_np`.


In [210]:
import time

rng = np.random.default_rng(6501)
n = 80
A = rng.normal(size=(n, n))

t0 = time.perf_counter()
inv_gj = gauss_jordan_inverse(A)
t1 = time.perf_counter()

t2 = time.perf_counter()
inv_np = np.linalg.inv(A)
t3 = time.perf_counter()

time_gj = t1 - t0
time_np = t3 - t2

print("time_gj (s):", time_gj)
print("time_np (s):", time_np)
print("ratio time_gj / time_np:", time_gj / time_np)


time_gj (s): 0.009415900000021793
time_np (s): 0.0003006000006280374
ratio time_gj / time_np: 31.32368589603908


---

## Question 3 — Cholesky Solver (40 pts)

Implement a Cholesky-based solver for SPD matrices.

### Requirements

Implement:

1. `cholesky_factor(A)` returning a lower-triangular matrix `L` such that
$$
\mathbf{A}=\mathbf{L}\mathbf{L}^T.
$$

2. `forward_substitution(L, b)` solving
$$
\mathbf{L}\hat{\mathbf{b}}=\mathbf{b}.
$$

3. `back_substitution(U, \hat{\mathbf{b}})` solving
$$
\mathbf{U}\mathbf{x}=\hat{\mathbf{b}},
\qquad \text{with } \mathbf{U}=\mathbf{L}^T.
$$

4. `solve_cholesky(A, b)` solving
$$
\mathbf{A}\mathbf{x}=\mathbf{b}
$$

### Notes
- You may **not** call `np.linalg.cholesky` inside your implementation.
- You may use `np.linalg.solve` in tests, but not inside your solver.

### Checks
You will test your solver on:
1. A 4×4 SPD matrix (same as the manual problems)
$$
\mathbf{K}=
\begin{bmatrix}
4 & 1 & 0 & 0 \\
1 & 3 & 1 & 0 \\
0 & 1 & 2 & 1 \\
0 & 0 & 1 & 2
\end{bmatrix}
$$
2. A larger random SPD matrix

✅ Deliverable: Implement `cholesky_factor` and `solve_cholesky` so the test cell passes.

In [211]:
# YOUR WORK

def cholesky_factor(A, tol=1e-14):
    """
    Return L such that A = L L^T for symmetric positive definite A.
    Uses the column-by-column construction discussed in class.
    """
    n = A.shape[0]
    L = np.zeros_like(A)

    for j in range(n):
        L[j, j] = np.sqrt(A[j, j] - np.dot(L[j, :j], L[j, :j]))
        for i in range(j + 1, n):
            L[i, j] = (A[i, j] - np.dot(L[i, :j], L[j, :j])) / L[j, j]
    return L
    # TODO: implement
    raise NotImplementedError


def forward_substitution(L, b, tol=1e-14):
    """
    Solve L b_hat = b for b_hat (L lower triangular).
    """
    n = L.shape[0]
    b_hat = np.zeros(n)

    for i in range(n):
        b_hat[i] = (b[i] - np.dot(L[i, :i], b_hat[:i])) / L[i, i]
    return b_hat
    # TODO: implement
    raise NotImplementedError


def back_substitution(U, b_hat, tol=1e-14):
    """
    Solve U x = b_hat for x (U upper triangular).
    """
    n = U.shape[0]
    x = np.zeros(n)

    for i in range(n-1, -1, -1):
        x[i] = (b_hat[i] - np.dot(U[i, i+1:], x[i+1:])) / U[i, i]
    return x
    # TODO: implement
    raise NotImplementedError


def solve_cholesky(A, b):
    """
    Solve A x = b using Cholesky factorization:
        1) A = L L^T
        2) L b_hat = b
        3) L^T x = b_hat
    """
    L = cholesky_factor(A)
    b_hat = forward_substitution(L, b)
    x = back_substitution(L.T, b_hat)
    return x
    # TODO: implement
    raise NotImplementedError


In [212]:
# ============================================================
#  TESTS — Do Not Edit
# ============================================================

print("\n--- Cholesky Solver Tests ---")

# ------------------------------------------------------------
# Manual test case (small SPD matrix + multiple RHS vectors)
# ------------------------------------------------------------

K = np.array([
    [4.0, 1.0, 0.0, 0.0],
    [1.0, 3.0, 1.0, 0.0],
    [0.0, 1.0, 2.0, 1.0],
    [0.0, 0.0, 1.0, 2.0],
])

b1 = np.array([1.0, 0.0, 0.0, 0.0])
b2 = np.array([0.0, 1.0, 0.0, 0.0])
b3 = np.array([1.0, 1.0, 1.0, 1.0])

print("\nSPD matrix K:")
print(K)

print("\nRight-hand sides:")
print("b1 =", b1)
print("b2 =", b2)
print("b3 =", b3)

# ------------------------------------------------------------
# Factorization check: K ?= L L^T
# ------------------------------------------------------------

L = cholesky_factor(K)

print("\nCholesky factor L (K = L L^T):")
print(L)

K_rebuild = L @ L.T
print("\nReconstructed K from L L^T:")
print(K_rebuild)

np.testing.assert_allclose(K, K_rebuild, rtol=1e-9, atol=1e-9)
print("✔ Factorization check passed")

# ------------------------------------------------------------
# Solve checks: compare to NumPy for multiple RHS vectors
# ------------------------------------------------------------

for i, b in enumerate([b1, b2, b3], start=1):
    x_hat = solve_cholesky(K, b)
    x_np = np.linalg.solve(K, b)

    print(f"\nSolution for b{i}:")
    print("x (Cholesky) =", x_hat)
    print("x (NumPy)   =", x_np)

    np.testing.assert_allclose(x_hat, x_np, rtol=1e-9, atol=1e-9)

    res = np.linalg.norm(K @ x_hat - b)
    print("Residual ||Kx - b|| =", res)
    assert res < 1e-8

print("\n✔ Manual SPD solves passed")

# ------------------------------------------------------------
# Larger random SPD test (sanity + scaling)
# ------------------------------------------------------------

print("\n--- Large random SPD test ---")

rng = np.random.default_rng(6501)
n = 60
M = rng.normal(size=(n, n))
A_spd = M.T @ M + 1e-3 * np.eye(n)  # SPD by construction
b = rng.normal(size=n)

x_hat = solve_cholesky(A_spd, b)
x_np = np.linalg.solve(A_spd, b)

np.testing.assert_allclose(x_hat, x_np, rtol=1e-7, atol=1e-7)

rel_res = np.linalg.norm(A_spd @ x_hat - b) / np.linalg.norm(b)
print("Relative residual (large system):", rel_res)

print("\n✅ Question 3 tests passed.")



--- Cholesky Solver Tests ---

SPD matrix K:
[[4. 1. 0. 0.]
 [1. 3. 1. 0.]
 [0. 1. 2. 1.]
 [0. 0. 1. 2.]]

Right-hand sides:
b1 = [1. 0. 0. 0.]
b2 = [0. 1. 0. 0.]
b3 = [1. 1. 1. 1.]

Cholesky factor L (K = L L^T):
[[2.       0.       0.       0.      ]
 [0.5      1.658312 0.       0.      ]
 [0.       0.603023 1.279204 0.      ]
 [0.       0.       0.781736 1.178511]]

Reconstructed K from L L^T:
[[4. 1. 0. 0.]
 [1. 3. 1. 0.]
 [0. 1. 2. 1.]
 [0. 0. 1. 2.]]
✔ Factorization check passed

Solution for b1:
x (Cholesky) = [ 0.28 -0.12  0.08 -0.04]
x (NumPy)   = [ 0.28 -0.12  0.08 -0.04]
Residual ||Kx - b|| = 3.925231146709438e-17

Solution for b2:
x (Cholesky) = [-0.12  0.48 -0.32  0.16]
x (NumPy)   = [-0.12  0.48 -0.32  0.16]
Residual ||Kx - b|| = 1.1102230246251565e-16

Solution for b3:
x (Cholesky) = [0.2 0.2 0.2 0.4]
x (NumPy)   = [0.2 0.2 0.2 0.4]
Residual ||Kx - b|| = 0.0

✔ Manual SPD solves passed

--- Large random SPD test ---
Relative residual (large system): 8.084705511597e-14



---

## Bonus — Point Gauss–Seidel (Optional) (+20 pts)

Implement the Point Gauss–Seidel iteration for solving
$$
\mathbf{A}\mathbf{x}=\mathbf{b}.
$$

### Requirements

- Function name: `gauss_seidel(A, b, x0=None, max_iter=50, tol=1e-8)`
- Must reuse newest available values immediately (Gauss–Seidel behavior)
- Return `(x, history)` where `history` stores residual norms per iteration

✅ Deliverable: pass the bonus test cell.


In [213]:
# YOUR WORK (optional)

def gauss_seidel(A, b, x0=None, max_iter=50, tol=1e-8):
    n = A.shape[0]

    x = np.zeros(n) if x0 is None else np.array(x0, dtype=float).copy()
    history = []

    for j in range(max_iter):
        for i in range(n):
            x[i] = (b[i] - np.dot(A[i, :i], x[:i]) - np.dot(A[i, i+1:], x[i+1:])) / A[i, i]

        r = b - A @ x
        res = np.linalg.norm(r)
        history.append(res)

        if res < tol:
            break

    return x, history
    # TODO: implement
    raise NotImplementedError


In [214]:
# ============================================================
#  TESTS — Do Not Edit
# ============================================================

print("\n--- Bonus: Gauss–Seidel Iterative Solver ---\n")

# SPD matrix (well-conditioned, guaranteed convergence)
K = np.array([
    [4.0, 1.0, 0.0, 0.0],
    [1.0, 3.0, 1.0, 0.0],
    [0.0, 1.0, 2.0, 1.0],
    [0.0, 0.0, 1.0, 2.0],
])

b = np.array([1.0, 1.0, 1.0, 1.0])
x0 = np.zeros(4)

# Run Gauss–Seidel
x_gs, hist = gauss_seidel(
    K,
    b,
    x0=x0,
    max_iter=200,
    tol=1e-10
)

# Reference solution
x_np = np.linalg.solve(K, b)

# ------------------------------------------------------------
# Structural checks
# ------------------------------------------------------------

assert isinstance(x_gs, np.ndarray), "x_gs must be a NumPy array"
assert isinstance(hist, list), "hist must be a Python list"
assert x_gs.shape == (4,), "x_gs must be a vector of length 4"
assert len(hist) >= 2, "Residual history must contain multiple iterations"

# ------------------------------------------------------------
# Numerical correctness
# ------------------------------------------------------------

np.testing.assert_allclose(
    x_gs, x_np,
    rtol=1e-7,
    atol=1e-7,
    err_msg="Gauss–Seidel solution does not match NumPy solve"
)

# Residual check (final solution must satisfy Ax ≈ b)
final_residual = np.linalg.norm(K @ x_gs - b)
assert final_residual < 1e-8, "Final residual is too large"

# ------------------------------------------------------------
# Convergence behavior
# ------------------------------------------------------------

# Residuals must be non-negative
assert all(r >= 0 for r in hist), "Residuals must be non-negative"

# Residual should decrease overall
assert hist[-1] < hist[0], "Residual did not decrease overall"

# Residual should decrease monotonically for this SPD system
for k in range(1, len(hist)):
    assert hist[k] <= hist[k-1] + 1e-14, (
        "Residual increased between iterations "
        f"{k-1} and {k}"
    )

# ------------------------------------------------------------
# Sanity checks on iteration count
# ------------------------------------------------------------

assert len(hist) < 200, "Solver did not converge within max_iter"
assert hist[-1] <= 1e-10, "Convergence tolerance not achieved"

print("Final solution x:")
print(x_gs)

print("\nFinal residual ||A x - b|| =", final_residual)
print("Number of iterations =", len(hist))

print("\n✅ Bonus tests passed.")



--- Bonus: Gauss–Seidel Iterative Solver ---

Final solution x:
[0.2 0.2 0.2 0.4]

Final residual ||A x - b|| = 6.677566226913654e-11
Number of iterations = 29

✅ Bonus tests passed.


---

## Reflection (Required)

In 3–6 sentences:

- What part felt easiest?
- What part felt hardest?
- Did anything surprise you (accuracy, speed, stability)?
- One bug you encountered and how you fixed it.
- One thing you still don’t understand.
- If you used collaboration or AI tools, briefly describe how.


YOUR TEXT ANSWER HERE:

---

- **What part felt easiest?**
- Of course the first one.
- **What part felt hardest?**
- Q2, Gauss-Hordan Eliminattion.Unlike other questions where you can find a general formula in your notes to complete the cycle, this one requires you to derive the loop and the termination condition yourself.
- **Did anything surprise you (accuracy, speed, stability)?**
- I was amazed by how efficient NumPy’s built-in solvers are. They ran 31 times faster than the manual method recommended in linear algebra, which really made me appreciate the wisdom and engineering of the people who built these tools.
- **One bug you encountered and how you fixed it.**
- The only bug was in the back substitution loop when writing the Cholesky factorization solver: I set the wrong stop value in the range(start, stop, step) call. Since I hadn’t used the range(start, stop, step) format for a long time, I initially set the stop point to 0. When I saw the message “Mismatched element 1/4,” I realized it needed to be -1 so that the loop would correctly include the case index = 0.
- **One thing you still don’t understand.**
- **If you used collaboration or AI tools, briefly describe how.**
- I forgot how to initialize a matrix; zeros_like() is what I asked ChatGPT. The residual calculation in the bonus section was also something ChatGPT told me.